name: Run

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    # install python
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run
      run: |
        python3 1.1.1.1.py